server.port=8080
spring.application.name=MasterPlanApi
spring.datasource.url=jdbc:postgresql://localhost:5432/masterplan_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver