server.port=8080
spring.application.name=MasterPlanApi
spring.datasource.url=jdbc:postgresql://localhost:5432/masterplan_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/v1/api-docs
jwt.secret=${MASTERPLAN_JWT_SECRET}
jwt.expiration=12
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.socket=TRACE
logging.level.org.springframework.messaging=TRACE
logging.level.api.masterplan.app=DEBUG
storage.path=${MASTERPLAN_FILES_STORAGE}
storage.encrypt-key=${MASTERPLAN_FILES_STORAGE_ENCRYPT_KEY}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
spring.servlet.multipart.resolve-lazily=true