{
 "title": "MasterPlanDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "INFO logs count",
   "type": "gauge",
   "description": "INFO logs count",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(module) (count_over_time({app=\"MasterPlanApi\"} |= `INFO` [$__range]))"
    }
   ]
  },
  {
   "title": "WARN  logs count",
   "type": "gauge",
   "description": "WARN logs count",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(module) (count_over_time({app=\"MasterPlanApi\"} |= `WARN` [$__range]))"
    }
   ]
  },
  {
   "title": "AdminRequestsModuleLogs",
   "type": "logs",
   "description": "AdminRequestsModule logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{module=\"adminRequestsModule\"} |= ``"
    }
   ]
  },
  {
   "title": "AuthModuleLogs",
   "type": "logs",
   "description": "AuthModule logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{module=\"authModule\"} |= ``"
    }
   ]
  },
  {
   "title": "EmploueeModuleLogs",
   "type": "logs",
   "description": "EmploueeModule Logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{module=\"employeeModule\"} |= ``"
    }
   ]
  },
  {
   "title": "FilesModuleLogs",
   "type": "logs",
   "description": "FilesModule logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{module=\"filesModule\"} |= ``"
    }
   ]
  },
  {
   "title": "NotificationModuleLogs",
   "type": "logs",
   "description": "NotificationModule Logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{module=\"notificationModule\"} |= ``"
    }
   ]
  },
  {
   "title": "PlanModuleLogs",
   "type": "logs",
   "description": "PlanModule Logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{module=\"planModule\"} |= ``"
    }
   ]
  },
  {
   "title": "ReportModuleLogs",
   "type": "logs",
   "description": "ReportModule Logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{module=\"reportModule\"} |= ``"
    }
   ]
  },
  {
   "title": "ReportModuleLogs",
   "type": "logs",
   "description": "ReportModule Logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{module=\"userManagementModule\"} |= ``"
    }
   ]
  }
 ]
}